CREATE TABLE CARE_PLANS (
    cp_id INT AUTO_INCREMENT,
    statement_id INT NOT NULL,
    hp_id INT NULL,
    status VARCHAR(50) NULL,
    intent VARCHAR(50) NULL,
    title VARCHAR(255) NULL,
    description TEXT NULL,
    period_start DATETIME NULL,
    period_end DATETIME NULL,
    condition_id INT NULL,
    cp_goal TEXT NULL,
    CONSTRAINT PK_CARE_PLANS PRIMARY KEY (cp_id),
    CONSTRAINT FK_CARE_PLANS_STATEMENT FOREIGN KEY (statement_id) REFERENCES CLINICAL_STATEMENT(statement_id) ON DELETE CASCADE,
    CONSTRAINT FK_CARE_PLANS_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL,
    CONSTRAINT FK_CARE_PLANS_CONDITION FOREIGN KEY (condition_id) REFERENCES HEALTH_CONDITIONS(condition_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;