CREATE TABLE CARE_PLAN_ACTIVITY (
    act_id INT AUTO_INCREMENT,
    cp_id INT NOT NULL,
    procedure_id INT NULL,
    hp_id INT NULL,
    act_kind VARCHAR(100) NULL,
    act_status VARCHAR(50) NULL,
    act_code VARCHAR(100) NULL,
    med_summary_id INT NULL,
    obs_id INT NULL,
    act_note TEXT NULL,
    scheduled_date DATETIME NULL,
    CONSTRAINT PK_CARE_PLAN_ACTIVITY PRIMARY KEY (act_id),
    CONSTRAINT FK_CPA_CARE_PLAN FOREIGN KEY (cp_id) REFERENCES CARE_PLANS(cp_id) ON DELETE CASCADE,
    CONSTRAINT FK_CPA_PROCEDURE FOREIGN KEY (procedure_id) REFERENCES PROCEDURES(procedure_id) ON DELETE SET NULL,
    CONSTRAINT FK_CPA_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL,
    CONSTRAINT FK_CPA_MED_SUM FOREIGN KEY (med_summary_id) REFERENCES MEDICATION_SUMMARY(med_summary_id) ON DELETE SET NULL,
    CONSTRAINT FK_CPA_OBS FOREIGN KEY (obs_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;