CREATE TABLE CLINICAL_STATEMENT (
    statement_id INT AUTO_INCREMENT,
    encounter_id INT NULL,
    patient_id INT NOT NULL,
    statement_type VARCHAR(100) NULL,
    gen_narr LONGTEXT NULL,
    empty_reason VARCHAR(255) NULL,
    note TEXT NULL,
    CONSTRAINT PK_CLINICAL_STATEMENT PRIMARY KEY (statement_id),
    CONSTRAINT FK_CLIN_STMT_ENCOUNTER FOREIGN KEY (encounter_id) REFERENCES ENCOUNTER(encounter_id) ON DELETE SET NULL,
    CONSTRAINT FK_CLIN_STMT_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;