CREATE TABLE DOSAGE_DETAILS (
    dosage_id INT AUTO_INCREMENT,
    med_summary_id INT NOT NULL,
    sequence INT NULL,
    rendered_instr TEXT NULL,
    dose_value DECIMAL(10,3) NULL,
    dose_unit_code VARCHAR(50) NULL,
    rate_ratio_num DECIMAL(10,3) NULL,
    rate_ratio_den DECIMAL(10,3) NULL,
    rate_unit_code VARCHAR(50) NULL,
    bounds_start DATETIME NULL,
    bounds_end DATETIME NULL,
    repeat_duration DECIMAL(10,2) NULL,
    rep_dur_unit VARCHAR(50) NULL,
    freq_count INT NULL,
    freq_period DECIMAL(10,2) NULL,
    freq_per_unit VARCHAR(50) NULL,
    day_of_week VARCHAR(50) NULL,
    time_of_day TIME NULL,
    event_time_code VARCHAR(50) NULL,
    as_needed TINYINT(1) NULL,
    route_code VARCHAR(100) NULL,
    body_site_id INT NULL,
    dosage_note TEXT NULL,
    CONSTRAINT PK_DOSAGE_DETAILS PRIMARY KEY (dosage_id),
    CONSTRAINT FK_DOSAGE_MED_SUM FOREIGN KEY (med_summary_id) REFERENCES MEDICATION_SUMMARY(med_summary_id) ON DELETE CASCADE,
    CONSTRAINT FK_DOSAGE_BODY_SITE FOREIGN KEY (body_site_id) REFERENCES BODY_STRUCTURE(body_site_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;