CREATE TABLE ENCOUNTER (
    encounter_id INT AUTO_INCREMENT,
    patient_id INT NOT NULL,
    hp_id INT NULL,
    org_id INT NOT NULL,
    start_date DATETIME NOT NULL,
    end_date DATETIME NULL,
    visit_type_code VARCHAR(100) NULL,
    visit_type_display VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ENCOUNTER PRIMARY KEY (encounter_id),
    CONSTRAINT FK_ENCOUNTER_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE,
    CONSTRAINT FK_ENCOUNTER_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL,
    CONSTRAINT FK_ENCOUNTER_ORG FOREIGN KEY (org_id) REFERENCES ORGANISATION(org_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;