CREATE TABLE FUNCTIONAL_STATUS_ASSESSMENT (
    patient_id INT NOT NULL,
    obs_result_id INT NOT NULL,
    CONSTRAINT PK_FUNCTIONAL_STATUS_ASSESSMENT PRIMARY KEY (patient_id, obs_result_id),
    CONSTRAINT FK_FSA_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE,
    CONSTRAINT FK_FSA_OBS_RES FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;