CREATE TABLE HEALTH_PRO_ROLE (
    role_id INT AUTO_INCREMENT,
    hp_id INT NOT NULL,
    org_id INT NOT NULL,
    role_code VARCHAR(100) NULL,
    role_display VARCHAR(255) NULL,
    specialty_code VARCHAR(100) NULL,
    specialty_display VARCHAR(255) NULL,
    valid_from DATE NULL,
    valid_to DATE NULL,
    CONSTRAINT PK_HEALTH_PRO_ROLE PRIMARY KEY (role_id),
    CONSTRAINT FK_HEALTH_PRO_ROLE_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE CASCADE,
    CONSTRAINT FK_HEALTH_PRO_ROLE_ORG FOREIGN KEY (org_id) REFERENCES ORGANISATION(org_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;