CREATE TABLE IMAGING_STUDY_MODALITY (
    study_mod_id INT AUTO_INCREMENT,
    imag_study_id INT NOT NULL,
    modality_code VARCHAR(100) NULL,
    modality_display VARCHAR(255) NULL,
    CONSTRAINT PK_IMAGING_STUDY_MODALITY PRIMARY KEY (study_mod_id),
    CONSTRAINT FK_STUDY_MOD_STUDY FOREIGN KEY (imag_study_id) REFERENCES IMAGING_STUDY(imag_study_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;