CREATE TABLE IMAGING_STUDY_ORDER (
    imag_study_id INT NOT NULL,
    service_req_id INT NOT NULL,
    CONSTRAINT PK_IMAGING_STUDY_ORDER PRIMARY KEY (imag_study_id, service_req_id),
    CONSTRAINT FK_IMAG_ORD_STUDY FOREIGN KEY (imag_study_id) REFERENCES IMAGING_STUDY(imag_study_id) ON DELETE CASCADE,
    CONSTRAINT FK_IMAG_ORD_SR FOREIGN KEY (service_req_id) REFERENCES SERVICE_REQUEST(service_req_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;