CREATE TABLE IMAGING_STUDY_BODY_SITE (
    imag_study_id INT NOT NULL,
    body_site_id INT NOT NULL,
    CONSTRAINT PK_IMAGING_STUDY_BODY_SITE PRIMARY KEY (imag_study_id, body_site_id),
    CONSTRAINT FK_IMAG_BS_STUDY FOREIGN KEY (imag_study_id) REFERENCES IMAGING_STUDY(imag_study_id) ON DELETE CASCADE,
    CONSTRAINT FK_IMAG_BS_SITE FOREIGN KEY (body_site_id) REFERENCES BODY_STRUCTURE(body_site_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;