CREATE TABLE IMAGING_STUDY_KEY_IMAGE (
    key_image_id INT AUTO_INCREMENT,
    instance_id INT NOT NULL,
    flag_code VARCHAR(100) NULL,
    flag_display VARCHAR(255) NULL,
    reason TEXT NULL,
    CONSTRAINT PK_IMAGING_STUDY_KEY_IMAGE PRIMARY KEY (key_image_id),
    CONSTRAINT FK_KEY_IMG_INSTANCE FOREIGN KEY (instance_id) REFERENCES IMAGING_STUDY_INSTANCE(instance_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;