CREATE TABLE IMAGING_SERIES_SPECIMEN (
    series_id INT NOT NULL,
    specimen_id INT NOT NULL,
    CONSTRAINT PK_IMAGING_SERIES_SPECIMEN PRIMARY KEY (series_id, specimen_id),
    CONSTRAINT FK_ISS_SERIES FOREIGN KEY (series_id) REFERENCES IMAGING_STUDY_SERIES(series_id) ON DELETE CASCADE,
    CONSTRAINT FK_ISS_SPECIMEN FOREIGN KEY (specimen_id) REFERENCES SPECIMEN(specimen_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;