CREATE TABLE IMMUNISATIONS (
    imm_id INT AUTO_INCREMENT,
    statement_id INT NOT NULL,
    disease_targeted VARCHAR(255) NULL,
    vaccine_type VARCHAR(100) NULL,
    dose_number INT NULL,
    status VARCHAR(50) NULL,
    lot_number VARCHAR(100) NULL,
    expiry_date DATE NULL,
    product_id INT NULL,
    administration_time DATETIME NULL,
    org_id INT NULL,
    hp_id INT NULL,
    CONSTRAINT PK_IMMUNISATIONS PRIMARY KEY (imm_id),
    CONSTRAINT FK_IMM_STATEMENT FOREIGN KEY (statement_id) REFERENCES CLINICAL_STATEMENT(statement_id) ON DELETE CASCADE,
    CONSTRAINT FK_IMM_PRODUCT FOREIGN KEY (product_id) REFERENCES PRODUCT_CATALOG(product_id) ON DELETE SET NULL,
    CONSTRAINT FK_IMM_ORGANIZATION FOREIGN KEY (org_id) REFERENCES ORGANISATION(org_id) ON DELETE SET NULL,
    CONSTRAINT FK_IMM_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;