CREATE TABLE MEDICATION_SUMMARY (
    med_summary_id INT AUTO_INCREMENT,
    statement_id INT NOT NULL,
    product_id INT NULL,
    summary_status VARCHAR(50) NULL,
    change_type VARCHAR(100) NULL,
    period_start DATETIME NULL,
    period_end DATETIME NULL,
    reason_text TEXT NULL,
    condition_id INT NULL,
    obs_id INT NULL,
    CONSTRAINT PK_MEDICATION_SUMMARY PRIMARY KEY (med_summary_id),
    CONSTRAINT FK_MED_SUM_STATEMENT FOREIGN KEY (statement_id) REFERENCES CLINICAL_STATEMENT(statement_id) ON DELETE CASCADE,
    CONSTRAINT FK_MED_SUM_PRODUCT FOREIGN KEY (product_id) REFERENCES PRODUCT_CATALOG (product_id) ON DELETE SET NULL,
    CONSTRAINT FK_MED_SUM_CONDITION FOREIGN KEY (condition_id) REFERENCES HEALTH_CONDITIONS(condition_id) ON DELETE SET NULL,
    CONSTRAINT FK_MED_SUM_OBS FOREIGN KEY (obs_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;