CREATE TABLE MEDICATION_PRESCRIPTION (
    prescription_id INT AUTO_INCREMENT,
    med_summary_id INT NOT NULL,
    dosage_id INT NULL,
    hp_id INT NULL,
    status_code VARCHAR(50) NULL,
    indication_code VARCHAR(100) NULL,
    intended_use_type VARCHAR(100) NULL,
    period_of_use_start DATETIME NULL,
    period_of_use_end DATETIME NULL,
    quantity_prescribed DECIMAL(10,2) NULL,
    quantity_unit VARCHAR(50) NULL,
    validity_period_start DATETIME NULL,
    validity_period_end DATETIME NULL,
    subst_allowed BOOLEAN NULL,
    subst_reason VARCHAR(255) NULL,
    number_of_repeats INT NULL,
    min_disp_interval VARCHAR(50) NULL,
    is_off_label BOOLEAN NULL,
    off_label_reason TEXT NULL,
    prescription_note TEXT NULL,
    CONSTRAINT PK_MEDICATION_PRESCRIPTION PRIMARY KEY (prescription_id),
    CONSTRAINT FK_PRESCR_MED_SUM FOREIGN KEY (med_summary_id) REFERENCES MEDICATION_SUMMARY(med_summary_id) ON DELETE CASCADE,
    CONSTRAINT FK_PRESCR_DOSAGE FOREIGN KEY (dosage_id) REFERENCES DOSAGE_DETAILS(dosage_id) ON DELETE SET NULL,
    CONSTRAINT FK_PRESCR_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;