CREATE TABLE OBS_PERFORMER (
    obs_performer_id INT AUTO_INCREMENT,
    obs_result_id INT NOT NULL,
    hp_id INT NULL,
    patient_id INT NULL,
    rp_id INT NULL,
    org_id INT NULL,
    function_code VARCHAR(100) NULL,
    actor_time DATETIME NULL,
    CONSTRAINT PK_OBS_PERFORMER PRIMARY KEY (obs_performer_id),
    CONSTRAINT FK_OBS_PERF_RESULT FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_PERF_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL,
    CONSTRAINT FK_OBS_PERF_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_PERF_RP FOREIGN KEY (rp_id) REFERENCES RELATED_PERSON(rp_id) ON DELETE SET NULL,
    CONSTRAINT FK_OBS_PERF_ORG FOREIGN KEY (org_id) REFERENCES ORGANISATION(org_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;