CREATE TABLE OBS_TRIGGERED_BY (
    obs_result_id INT NOT NULL,
    trigg_obs_result_id INT NOT NULL,
    trigg_type VARCHAR(100) NULL,
    CONSTRAINT PK_OBS_TRIGGERED_BY PRIMARY KEY (obs_result_id, trigg_obs_result_id),
    CONSTRAINT FK_OBS_TRIG_TARGET FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_TRIG_SOURCE FOREIGN KEY (trigg_obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;