CREATE TABLE OBS_INTERPRETATION (
    interpretation_id INT AUTO_INCREMENT,
    obs_result_id INT NULL,
    component_id INT NULL,
    interpretation_code VARCHAR(100) NULL,
    interpretation_display VARCHAR(255) NULL,
    CONSTRAINT PK_OBS_INTERPRETATION PRIMARY KEY (interpretation_id),
    CONSTRAINT FK_OBS_INTERP_RESULT FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_INTERP_COMP FOREIGN KEY (component_id) REFERENCES OBSERVATION_COMPONENT(component_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;