CREATE TABLE OBSERVATION_STATEMENT (
    obs_statement_id INT AUTO_INCREMENT,
    patient_id INT NOT NULL,
    encounter_id INT NULL,
    hp_id INT NULL,
    obs_type VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL,
    issued DATETIME NULL,
    effective_datetime DATETIME NULL,
    CONSTRAINT PK_OBSERVATION_STATEMENT PRIMARY KEY (obs_statement_id),
    CONSTRAINT FK_OBS_STMT_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_STMT_ENCOUNTER FOREIGN KEY (encounter_id) REFERENCES ENCOUNTER(encounter_id) ON DELETE SET NULL,
    CONSTRAINT FK_OBS_STMT_HP FOREIGN KEY (hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;