CREATE TABLE OBSERVATION_DERIVED_FROM (
    derived_id INT AUTO_INCREMENT,
    obs_result_id INT NOT NULL,
    source_obs_result_id INT NULL,
    imag_study_id INT NULL,
    derivation_type VARCHAR(100) NULL,
    CONSTRAINT PK_OBSERVATION_DERIVED_FROM PRIMARY KEY (derived_id),
    CONSTRAINT FK_OBS_DERIVED_TARGET FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_DERIVED_SOURCE FOREIGN KEY (source_obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;