CREATE TABLE OBSERVATION_RESULTS (
    obs_result_id INT AUTO_INCREMENT,
    obs_statement_id INT NOT NULL,
    specimen_id INT NULL,
    service_req_id INT NULL,
    body_site_id INT NULL,
    obs_date_start DATETIME NULL,
    obs_date_end DATETIME NULL,
    obs_type_code VARCHAR(100) NULL,
    obs_type_display VARCHAR(255) NULL,
    original_name VARCHAR(255) NULL,
    method_code VARCHAR(100) NULL,
    method_display VARCHAR(255) NULL,
    value_string TEXT NULL,
    value_quantity DECIMAL(15,4) NULL,
    value_unit VARCHAR(50) NULL,
    value_code VARCHAR(100) NULL,
    value_display VARCHAR(255) NULL,
    uncertainty_value DECIMAL(10,4) NULL,
    uncertainty_type_code VARCHAR(100) NULL,
    data_absent_reason_code VARCHAR(100) NULL,
    data_absent_reason_display VARCHAR(255) NULL,
    obs_result_note TEXT NULL,
    CONSTRAINT PK_OBSERVATION_RESULTS PRIMARY KEY (obs_result_id),
    CONSTRAINT FK_OBS_RES_STATEMENT FOREIGN KEY (obs_statement_id) REFERENCES OBSERVATION_STATEMENT(obs_statement_id) ON DELETE CASCADE,
    CONSTRAINT FK_OBS_RES_SPECIMEN FOREIGN KEY (specimen_id) REFERENCES SPECIMEN(specimen_id) ON DELETE SET NULL,
    CONSTRAINT FK_OBS_RES_SERVICE_REQ FOREIGN KEY (service_req_id) REFERENCES SERVICE_REQUEST(service_req_id) ON DELETE SET NULL,
    CONSTRAINT FK_OBS_RES_BODY_SITE FOREIGN KEY (body_site_id) REFERENCES BODY_STRUCTURE(body_site_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;