CREATE TABLE RELATED_PERSON (
    rp_id INT AUTO_INCREMENT,
    patient_id INT NOT NULL,
    rp_identifier VARCHAR(100) NULL,
    relationship_code VARCHAR(50) NULL,
    relationship_display VARCHAR(100) NULL,
    name_prefix VARCHAR(50) NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    name_suffix VARCHAR(50) NULL,
    display_name VARCHAR(255) NULL,
    name_use VARCHAR(50) NULL,
    addr_street VARCHAR(150) NULL,
    addr_num VARCHAR(20) NULL,
    addr_postbox VARCHAR(50) NULL,
    addr_city VARCHAR(100) NULL,
    addr_zip VARCHAR(20) NULL,
    addr_country VARCHAR(100) NULL,
    addr_display_text VARCHAR(255) NULL,
    addr_use VARCHAR(50) NULL,
    addr_type VARCHAR(50) NULL,
    phone_contact VARCHAR(50) NULL,
    phone_use VARCHAR(50) NULL,
    email_contact VARCHAR(100) NULL,
    email_use VARCHAR(50) NULL,
    CONSTRAINT PK_RELATED_PERSON PRIMARY KEY (rp_id),
    CONSTRAINT FK_RELATED_PERSON_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;