CREATE TABLE SERVICE_REQ_BODY_SITE (
    service_req_id INT NOT NULL,
    body_site_id INT NOT NULL,
    CONSTRAINT PK_SERVICE_REQ_BODY_SITE PRIMARY KEY (service_req_id, body_site_id),
    CONSTRAINT FK_SR_BS_SERVICE FOREIGN KEY (service_req_id) REFERENCES SERVICE_REQUEST(service_req_id) ON DELETE CASCADE,
    CONSTRAINT FK_SR_BS_SITE FOREIGN KEY (body_site_id) REFERENCES BODY_STRUCTURE(body_site_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;