CREATE TABLE SERVICE_REQUEST (
    service_req_id INT AUTO_INCREMENT,
    description TEXT NULL,
    status VARCHAR(50) NOT NULL,
    intent VARCHAR(50) NOT NULL,
    category_code VARCHAR(100) NULL,
    category_display VARCHAR(255) NULL,
    code_code VARCHAR(100) NULL,
    code_display VARCHAR(255) NULL,
    quant_value DECIMAL(10,3) NULL,
    quant_comparator VARCHAR(10) NULL,
    quant_unit VARCHAR(50) NULL,
    quant_system VARCHAR(255) NULL,
    quant_code VARCHAR(100) NULL,
    priority_code VARCHAR(50) NULL,
    priority_display VARCHAR(100) NULL,
    encounter_id INT NULL,
    patient_id INT NOT NULL,
    occur_date DATE NULL,
    occur_start DATETIME NULL,
    occur_end DATETIME NULL,
    patient_instructions TEXT NULL,
    authored_on DATETIME NULL,
    requester_hp_id INT NULL,
    requester_org_id INT NULL,
    CONSTRAINT PK_SERVICE_REQUEST PRIMARY KEY (service_req_id),
    CONSTRAINT FK_SR_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE,
    CONSTRAINT FK_SR_ENCOUNTER FOREIGN KEY (encounter_id) REFERENCES ENCOUNTER(encounter_id) ON DELETE SET NULL,
    CONSTRAINT FK_SR_HP FOREIGN KEY (requester_hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL,
    CONSTRAINT FK_SR_ORG FOREIGN KEY (requester_org_id) REFERENCES ORGANISATION(org_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;