CREATE TABLE SERVICE_REQ_SUPPORTING_INFO (
    supp_info_id INT AUTO_INCREMENT,
    service_req_id INT NOT NULL,
    obs_result_id INT NULL,
    condition_id INT NULL,
    procedure_id INT NULL,
    admin_id INT NULL,
    CONSTRAINT PK_SERVICE_REQ_SUPP_INFO PRIMARY KEY (supp_info_id),
    CONSTRAINT FK_SRSI_SERVICE_REQ FOREIGN KEY (service_req_id) REFERENCES SERVICE_REQUEST(service_req_id) ON DELETE CASCADE,
    CONSTRAINT FK_SRSI_OBS_RESULT FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE SET NULL,
    CONSTRAINT FK_SRSI_CONDITION FOREIGN KEY (condition_id) REFERENCES HEALTH_CONDITIONS(condition_id) ON DELETE SET NULL,
    CONSTRAINT FK_SRSI_PROCEDURE FOREIGN KEY (procedure_id) REFERENCES PROCEDURES(procedure_id) ON DELETE SET NULL,
    CONSTRAINT FK_SRSI_ADMIN FOREIGN KEY (admin_id) REFERENCES MEDICATION_ADMINISTRATION(admin_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;