CREATE TABLE SERVICE_REQ_REASON (
    reason_id INT AUTO_INCREMENT,
    service_req_id INT NOT NULL,
    reason_code VARCHAR(100) NULL,
    reason_display VARCHAR(255) NULL,
    obs_result_id INT NULL,
    med_summary_id INT NULL,
    CONSTRAINT PK_SERVICE_REQ_REASON PRIMARY KEY (reason_id),
    CONSTRAINT FK_SRR_SERVICE_REQ FOREIGN KEY (service_req_id) REFERENCES SERVICE_REQUEST(service_req_id) ON DELETE CASCADE,
    CONSTRAINT FK_SRR_OBS_RESULT FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE SET NULL,
    CONSTRAINT FK_SRR_MED_SUMMARY FOREIGN KEY (med_summary_id) REFERENCES MEDICATION_SUMMARY(med_summary_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;