CREATE TABLE SOCIAL_HISTORY_OBSERVATION (
    social_history_id INT NOT NULL,
    obs_result_id INT NOT NULL,
    CONSTRAINT PK_SOCIAL_HISTORY_OBSERVATION PRIMARY KEY (social_history_id, obs_result_id),
    CONSTRAINT FK_SHO_SOC_HIST FOREIGN KEY (social_history_id) REFERENCES SOCIAL_HISTORY(social_history_id) ON DELETE CASCADE,
    CONSTRAINT FK_SHO_OBS_RES FOREIGN KEY (obs_result_id) REFERENCES OBSERVATION_RESULTS(obs_result_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;