CREATE TABLE SPECIMEN_REQUEST (
    specimen_id INT NOT NULL,
    service_req_id INT NOT NULL,
    CONSTRAINT PK_SPECIMEN_REQUEST PRIMARY KEY (specimen_id, service_req_id),
    CONSTRAINT FK_SPEC_REQ_SPECIMEN FOREIGN KEY (specimen_id) REFERENCES SPECIMEN(specimen_id) ON DELETE CASCADE,
    CONSTRAINT FK_SPEC_REQ_SERVICE FOREIGN KEY (service_req_id) REFERENCES SERVICE_REQUEST(service_req_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;