CREATE TABLE SPECIMEN_CONDITION (
    specimen_cond_id INT AUTO_INCREMENT,
    specimen_id INT NOT NULL,
    condition_code VARCHAR(100) NULL,
    condition_display VARCHAR(255) NULL,
    CONSTRAINT PK_SPECIMEN_CONDITION PRIMARY KEY (specimen_cond_id),
    CONSTRAINT FK_SPEC_COND_SPECIMEN FOREIGN KEY (specimen_id) REFERENCES SPECIMEN(specimen_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;