CREATE TABLE SPECIMEN_IDENTIFIER (
    specimen_identifier_id INT AUTO_INCREMENT,
    specimen_id INT NOT NULL,
    org_id INT NULL,
    use_code VARCHAR(50) NULL,
    type_code VARCHAR(100) NULL,
    type_display VARCHAR(255) NULL,
    id_system VARCHAR(255) NULL,
    value VARCHAR(255) NOT NULL,
    period_start DATETIME NULL,
    period_end DATETIME NULL,
    CONSTRAINT PK_SPECIMEN_IDENTIFIER PRIMARY KEY (specimen_identifier_id),
    CONSTRAINT FK_SPEC_IDENT_SPECIMEN FOREIGN KEY (specimen_id) REFERENCES SPECIMEN(specimen_id) ON DELETE CASCADE,
    CONSTRAINT FK_SPEC_IDENT_ORG FOREIGN KEY (org_id) REFERENCES ORGANISATION(org_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;