CREATE TABLE SPECIMEN (
    specimen_id INT AUTO_INCREMENT,
    status_code VARCHAR(50) NULL,
    status_display VARCHAR(100) NULL,
    type_code VARCHAR(100) NULL,
    type_display VARCHAR(255) NULL,
    patient_id INT NOT NULL,
    loc_id INT NULL,
    device_id VARCHAR(100) NULL,
    combined_code VARCHAR(100) NULL,
    combined_display VARCHAR(255) NULL,
    collector_hp_id INT NULL,
    collector_org_id INT NULL,
    collector_patient_id INT NULL,
    collector_rp_id INT NULL,
    collected_datetime DATETIME NULL,
    collected_period_end DATETIME NULL,
    collection_quant_value DECIMAL(10,3) NULL,
    collection_quant_unit VARCHAR(50) NULL,
    collection_method_code VARCHAR(100) NULL,
    collection_method_display VARCHAR(255) NULL,
    collection_device_id VARCHAR(100) NULL,
    received_date DATETIME NULL,
    body_site_id INT NULL,
    note TEXT NULL,
    CONSTRAINT PK_SPECIMEN PRIMARY KEY (specimen_id),
    CONSTRAINT FK_SPECIMEN_PATIENT FOREIGN KEY (patient_id) REFERENCES PATIENT(patient_id) ON DELETE CASCADE,
    CONSTRAINT FK_SPECIMEN_LOCATION FOREIGN KEY (loc_id) REFERENCES LOCATION(loc_id) ON DELETE SET NULL,
    CONSTRAINT FK_SPECIMEN_HP FOREIGN KEY (collector_hp_id) REFERENCES HEALTH_PROFESSIONAL(hp_id) ON DELETE SET NULL,
    CONSTRAINT FK_SPECIMEN_ORG FOREIGN KEY (collector_org_id) REFERENCES ORGANISATION(org_id) ON DELETE SET NULL,
    CONSTRAINT FK_SPECIMEN_RP FOREIGN KEY (collector_rp_id) REFERENCES RELATED_PERSON(rp_id) ON DELETE SET NULL,
    CONSTRAINT FK_SPECIMEN_BODY_SITE FOREIGN KEY (body_site_id) REFERENCES BODY_STRUCTURE(body_site_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;